GET http://localhost:3000/products

###

POST http://localhost:3000/products
content-type: application/json

{
    "description": "Mydfdsfdsdlo",
    "src": "https://picsum.photos/id/14/100/200",
    "price": 9055
}

###

DELETE http://localhost:3000/products/1